# Generated by Django 3.2.19 on 2023-06-22 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publication_year',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterModelTable(
            name='book',
            table='book',
        ),
    ]
