# Generated by Django 3.2.19 on 2023-06-22 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20230622_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='book',
            name='publication_year',
            field=models.PositiveIntegerField(max_length=4),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterModelTable(
            name='book',
            table=None,
        ),
    ]
